/* Ruby Chan — Supabase character chat client + Energy */
(function () {
  'use strict';
  const SUPABASE_URL='https://hcbajvladlvhklelbxdr.supabase.co';
  const SUPABASE_KEY='sb_publishable_eKKXyB0rc7QUwTbbydi8Xw_t0n27eIj';
  const db=window.supabaseClient||(window.supabase?.createClient?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null);
  let activeCharacter=null,activeConversation=null,energy=null;
  function esc(v){return String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function updateTopEnergy(v){if(v==null||Number.isNaN(Number(v)))return;energy=Number(v);const e=document.getElementById('energyValue');if(e)e.textContent=String(energy);}
  async function getUser(){if(!db)return null;const {data,error}=await db.auth.getUser();if(error)throw error;return data?.user||null;}
  async function getProfile(user){const {data,error}=await db.from('profiles').select('id,energy').eq('id',user.id).maybeSingle();if(error)throw new Error('Could not load profile: '+error.message);if(!data)throw new Error('Profile not found for this account.');return data;}
  async function refreshEnergy(){if(!db)return;try{const u=await getUser();if(!u)return;updateTopEnergy((await getProfile(u)).energy);}catch(e){console.warn('Energy refresh failed:',e?.message||e);}}
  function ensureStyles(){if(document.getElementById('ruby-energy-style'))return;const s=document.createElement('style');s.id='ruby-energy-style';s.textContent=`#rubyKindroidChat{position:fixed;inset:0;z-index:10000;background:#f2f2f7;display:none;flex-direction:column}#rubyKindroidChat.open{display:flex}.rk-head{height:64px;display:flex;align-items:center;gap:12px;padding:10px 14px;background:rgba(255,255,255,.97);border-bottom:1px solid rgba(60,60,67,.12)}.rk-back{border:0;background:#f2f2f7;border-radius:12px;width:40px;height:40px;font-size:22px;cursor:pointer}.rk-head-info{min-width:0;flex:1}.rk-title{font-weight:800;font-size:17px}.rk-status{font-size:11px;color:#34c759;margin-top:2px}.rk-messages{flex:1;overflow-y:auto;padding:18px 14px 100px;display:flex;flex-direction:column;gap:9px}.rk-bubble{max-width:82%;padding:10px 13px;border-radius:17px;font-size:14px;line-height:1.5;white-space:pre-wrap;word-break:break-word}.rk-user{align-self:flex-end;background:#7c3aed;color:#fff;border-bottom-right-radius:5px}.rk-ai{align-self:flex-start;background:#fff;border:1px solid rgba(60,60,67,.10);border-bottom-left-radius:5px}.rk-compose{position:fixed;left:0;right:0;bottom:0;padding:10px 12px;background:rgba(255,255,255,.97);border-top:1px solid rgba(60,60,67,.12);display:flex;gap:8px}.rk-input{flex:1;border:1px solid #d1d1d6;border-radius:20px;padding:10px 13px;font:inherit;outline:none}.rk-send{width:44px;border:0;border-radius:50%;background:#7c3aed;color:#fff;font-size:18px}.rk-send:disabled{opacity:.45}.rk-empty{margin:auto;color:#8e8e93;text-align:center}.rk-error{align-self:center;color:#ff3b30;font-size:12px;text-align:center;padding:10px}`;document.head.appendChild(s);}
  function ensureUI(){let r=document.getElementById('rubyKindroidChat');if(r)return r;r=document.createElement('div');r.id='rubyKindroidChat';r.innerHTML=`<div class="rk-head"><button class="rk-back" id="rkBack" type="button">‹</button><div class="rk-head-info"><div class="rk-title" id="rkTitle">Ruby Chan</div><div class="rk-status">● AI Chat</div></div></div><div class="rk-messages" id="rkMessages"><div class="rk-empty">Start a conversation ✨</div></div><form class="rk-compose" id="rkForm"><input class="rk-input" id="rkInput" autocomplete="off" placeholder="Message..."><button class="rk-send" id="rkSend" type="submit">➤</button></form>`;document.body.appendChild(r);r.querySelector('#rkBack').onclick=()=>r.classList.remove('open');r.querySelector('#rkForm').addEventListener('submit',sendMessage);return r;}
  function render(ms){const b=document.getElementById('rkMessages');if(!b)return;b.innerHTML='';if(!ms.length){b.innerHTML='<div class="rk-empty">Start a conversation ✨</div>';return;}ms.forEach(m=>{const d=document.createElement('div');d.className='rk-bubble '+(m.role==='user'?'rk-user':'rk-ai');d.innerHTML=esc(m.content);b.appendChild(d);});b.scrollTop=b.scrollHeight;}
  async function loadMessages(id){if(!db||!id)return;const r=await db.from('messages').select('role,content,created_at').eq('conversation_id',id).order('created_at',{ascending:true});if(!r.error)render(r.data||[]);}
  async function openChat(detail){activeCharacter=detail.character;activeConversation=detail.conversation||null;if(!activeConversation?.id&&window.rubyCurrentConversation)activeConversation={id:window.rubyCurrentConversation};const r=ensureUI();r.querySelector('#rkTitle').textContent=activeCharacter||'Ruby Chan';r.classList.add('open');render(detail.messages||[]);await refreshEnergy();if(activeConversation?.id)await loadMessages(activeConversation.id);}
  async function findCharacter(name){if(!db||!name)return null;const {data,error}=await db.from('characters').select('id,name').eq('name',name).limit(1).maybeSingle();if(error)throw new Error('Could not load character: '+error.message);if(!data?.id)throw new Error('Character not found: '+name);return data;}
  async function sendMessage(e){e.preventDefault();const input=document.getElementById('rkInput'),send=document.getElementById('rkSend'),msg=input?.value.trim();if(!msg||!activeCharacter||!db)return;try{const u=await getUser();if(!u)throw new Error('Please login first.');const p=await getProfile(u);energy=Number(p.energy||0);updateTopEnergy(energy);if(energy<=0)return;}catch(err){const b=document.getElementById('rkMessages');if(b){const x=document.createElement('div');x.className='rk-error';x.textContent='Chat error: '+(err?.message||err);b.appendChild(x);}return;}if(!activeConversation?.id&&window.rubyCurrentConversation)activeConversation={id:window.rubyCurrentConversation};input.value='';send.disabled=true;const b=document.getElementById('rkMessages'),ub=document.createElement('div');ub.className='rk-bubble rk-user';ub.textContent=msg;b.appendChild(ub);b.scrollTop=b.scrollHeight;try{const ch=await findCharacter(activeCharacter);const {data,error}=await db.functions.invoke('chat',{body:{character_id:ch.id,message:msg,conversation_id:activeConversation?.id||null}});if(error){let d=error.message||String(error);if(error.context){try{const rb=await error.context.json();if(rb?.error)d=rb.details?`${rb.error}: ${rb.details}`:rb.error;}catch(_){}}throw new Error(d);}const reply=data?.reply||'';if(!reply)throw new Error('AI returned an empty reply');await refreshEnergy();if(activeConversation?.id)await loadMessages(activeConversation.id);else if(window.rubyCurrentConversation){activeConversation={id:window.rubyCurrentConversation};await loadMessages(activeConversation.id);}else{const a=document.createElement('div');a.className='rk-bubble rk-ai';a.textContent=reply;b.appendChild(a);b.scrollTop=b.scrollHeight;}}catch(err){const x=document.createElement('div');x.className='rk-error';x.textContent='Chat error: '+(err?.message||err);b.appendChild(x);input.value=msg;await refreshEnergy();}finally{send.disabled=false;input.focus();}}
  window.addEventListener('rubychat:open',e=>openChat(e.detail||{}));window.addEventListener('rubychat:loaded',e=>openChat(e.detail||{}));
  function init(){ensureStyles();ensureUI();refreshEnergy();if(db)db.auth.onAuthStateChange(()=>setTimeout(refreshEnergy,0));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();