/* Ruby Chan — Unified Supabase Chat History Sync (single shared client) */
(function(){
  const db = window.supabaseClient || window.rubySupabase || null;
  if (!db) {
    console.error('Ruby Chan Chat Sync: shared Supabase client is unavailable.');
    return;
  }

  let currentUser=null, historyCharacterFilter=null, booted=false;
  const images={Sakura:'https://i.pinimg.com/originals/bf/ef/23/bfef23375344609c048165a7e7ae150b.jpg',Yuna:'https://i.pinimg.com/564x/ab/4f/c7/ab4fc790bddb89dc9b006e1e4a9c3e2.jpg',Rin:'https://media.easy-peasy.ai/27feb2bb-aeb4-4a83-9fb6-8f3f2a15885e/59b1c9a8-392b-4d9a-84d0-f075091ffa1b.png',Akari:'https://i-blog.csdnimg.cn/blog_migrate/332cc1a83679e50899b6045e2bb3cece.png',Hana:'https://c-ssl.duitang.com/uploads/blog/202306/14/Q2SDz364f8YX0jM.jpg',Reina:'https://c-ssl.duitang.com/uploads/blog/202305/01/20230501125015_95235.jpg'};
  function esc(v){return String(v??'').replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));}
  function loginRequired(){alert('🔐 Please log in or create an account to start chatting.');document.getElementById('rubyAuthButton')?.click()}
  async function getUser(){if(currentUser)return currentUser;const r=await db.auth.getSession();currentUser=r.data.session?.user||null;return currentUser}
  async function ensureConversation(character){if(!currentUser||!character)return null;let r=await db.from('conversations').select('*').eq('user_id',currentUser.id).eq('character_id',character).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;if(r.data)return r.data;r=await db.from('conversations').insert({user_id:currentUser.id,character_id:character,title:character+' Chat'}).select().single();if(r.error)throw r.error;return r.data}
  async function createNewConversation(character){if(!currentUser||!character)return null;const r=await db.from('conversations').insert({user_id:currentUser.id,character_id:character,title:'New '+character}).select().single();if(r.error)throw r.error;return r.data}
  async function addMessage(conversationId,role,content){if(!currentUser||!conversationId||!content)return false;const r=await db.from('messages').insert({conversation_id:conversationId,user_id:currentUser.id,role,content});if(r.error)return false;db.from('conversations').update({updated_at:new Date().toISOString()}).eq('id',conversationId).eq('user_id',currentUser.id);return true}
  function ensureHistoryStyle(){if(document.getElementById('ruby-unified-history-premium-style'))return;const s=document.createElement('style');s.id='ruby-unified-history-premium-style';s.textContent='.ruby-unified-history{position:relative;border:1px solid rgba(124,58,237,.18)!important;background:linear-gradient(135deg,rgba(255,255,255,.98),rgba(250,245,255,.98))!important;box-shadow:0 8px 24px rgba(124,58,237,.08);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.ruby-unified-history:hover{transform:translateY(-1px);border-color:rgba(124,58,237,.34)!important;box-shadow:0 12px 30px rgba(124,58,237,.14)}.ruby-history-actions{display:flex;align-items:center;gap:6px;margin-left:auto;flex:0 0 auto}.ruby-history-new-btn{border:0;border-radius:10px;padding:7px 9px;background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;font-size:10px;font-weight:850;cursor:pointer;white-space:nowrap}.ruby-new-chat-btn{margin-left:auto;flex:0 0 auto;border:0;border-radius:12px;padding:8px 10px;background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;font-size:11px;font-weight:800;cursor:pointer}.ruby-new-chat-btn:disabled{opacity:.55;cursor:default}';document.head.appendChild(s)}
  function ensureNewChatButton(){ensureHistoryStyle();const head=document.querySelector('#rubyKindroidChat .rk-head');if(!head||head.querySelector('#rubyNewChatBtn'))return;const btn=document.createElement('button');btn.id='rubyNewChatBtn';btn.type='button';btn.className='ruby-new-chat-btn';btn.textContent='＋ New';btn.onclick=startNewChat;head.appendChild(btn)}
  async function startNewChat(){if(!await getUser())return loginRequired();const character=window.rubyCurrentCharacter;if(!character)return;const btn=document.getElementById('rubyNewChatBtn');if(btn)btn.disabled=true;try{const c=await createNewConversation(character);window.rubyCurrentConversation=c?.id||null;window.rubyChatMessages=[];historyCharacterFilter=null;switchPage('chat');window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character,conversation:c,messages:[]}}));loadHistory(true)}catch(e){console.error(e);alert('Could not start a new chat. Please try again')}finally{if(btn)btn.disabled=false}}
  async function loadHistory(silent){if(!currentUser)return;const list=document.getElementById('chatHistoryList');if(!list)return;ensureHistoryStyle();let q=db.from('conversations').select('id,character_id,title,updated_at').eq('user_id',currentUser.id).order('updated_at',{ascending:false}).limit(100);if(historyCharacterFilter)q=q.eq('character_id',historyCharacterFilter);const r=await q;if(r.error)return;list.innerHTML='';if(historyCharacterFilter){const filter=document.createElement('div');filter.className='ruby-history-filter';filter.innerHTML='💜 '+esc(historyCharacterFilter)+' history <button type="button">All Characters</button>';filter.querySelector('button').onclick=function(){historyCharacterFilter=null;loadHistory()};list.appendChild(filter)}if(!r.data?.length){const empty=document.createElement('div');empty.className='chat-empty';empty.innerHTML=historyCharacterFilter?'💬<br><span>No '+esc(historyCharacterFilter)+' history yet.</span>':'💬<br><span>No chat history yet.</span>';list.appendChild(empty);return}r.data.forEach(c=>{const row=document.createElement('div');row.className='chat-history-item ruby-unified-history';row.style.cursor='pointer';row.innerHTML='<img class="chat-history-avatar" src="'+(images[c.character_id]||images.Sakura)+'" alt="'+esc(c.character_id)+'"><div class="chat-history-info"><div class="chat-history-name">'+esc(c.title||('Chat with '+c.character_id))+'</div><div class="chat-history-preview">'+esc(c.character_id)+' • Continue this conversation</div></div><div class="ruby-history-actions"><span class="chat-history-time">'+new Date(c.updated_at).toLocaleDateString()+'</span><button type="button" class="ruby-history-new-btn">New '+esc(c.character_id)+'</button></div>';row.onclick=function(){openConversation(c)};row.querySelector('.ruby-history-new-btn').onclick=function(e){e.stopPropagation();window.rubyStartNewCharacterChat(c.character_id)};list.appendChild(row)})}
  async function openConversation(c){if(!await getUser())return loginRequired();window.rubyCurrentConversation=c.id;window.rubyCurrentCharacter=c.character_id;historyCharacterFilter=null;switchPage('chat');const r=await db.from('messages').select('role,content,created_at').eq('conversation_id',c.id).order('created_at',{ascending:true});window.rubyChatMessages=r.error?[]:(r.data||[]);ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:loaded',{detail:{character:c.character_id,conversation:c,messages:window.rubyChatMessages}}))}
  window.rubyStartNewCharacterChat=async function(character){if(!await getUser())return loginRequired();try{const c=await createNewConversation(character);window.rubyCurrentConversation=c?.id||null;window.rubyCurrentCharacter=character;window.rubyChatMessages=[];historyCharacterFilter=null;switchPage('chat');ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character,conversation:c,messages:[]}}));loadHistory(true)}catch(e){console.error(e);alert('Could not start a new chat. Please try again.')}};
  window.rubyShowCharacterHistory=async function(character){if(!await getUser())return loginRequired();historyCharacterFilter=character;switchPage('chat');loadHistory(true)};
  window.rubyChatSaveMessage=async function(role,content){if(!await getUser())return false;let id=window.rubyCurrentConversation;if(!id){const c=await ensureConversation(window.rubyCurrentCharacter||'Unknown');id=c?.id;window.rubyCurrentConversation=id}if(!id)return false;const ok=await addMessage(id,role,content);loadHistory(true);return ok};
  window.rubyLoadChatHistory=loadHistory;
  window.startChat=async function(character){if(!await getUser())return loginRequired();window.rubyCurrentCharacter=character;try{const c=await ensureConversation(character);window.rubyCurrentConversation=c?.id||null;historyCharacterFilter=null;switchPage('chat');ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character,conversation:c}}))}catch(e){console.error(e);alert('Could not open this conversation. Please try again.')}};
  db.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;if(currentUser){setTimeout(()=>loadHistory(true),0)}else{window.rubyCurrentConversation=null;window.rubyCurrentCharacter=null}});
  function boot(){if(booted)return;booted=true;setTimeout(async()=>{await getUser();if(currentUser)loadHistory(true)},0)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
