/* Ruby Chan — Unified Supabase Chat History Sync */
(function(){
  const db=window.supabaseClient||window.rubySupabase||null;if(!db)return;
  let currentUser=null,historyCharacterFilter=null,booted=false;
  const images={Sakura:'https://i.pinimg.com/originals/bf/ef/23/bfef23375344609c048165a7e7ae150b.jpg',Yuna:'https://i.pinimg.com/564x/ab/4f/c7/ab4fc790bddb89dc9b006e1e4a9c3e2.jpg',Rin:'https://media.easy-peasy.ai/27feb2bb-aeb4-4a83-9fb6-8f3f2a15885e/59b1c9a8-392b-4d9a-84d0-f075091ffa1b.png',Akari:'https://i-blog.csdnimg.cn/blog_migrate/332cc1a83679e50899b6045e2bb3cece.png',Hana:'https://c-ssl.duitang.com/uploads/blog/202306/14/Q2SDz364f8YX0jM.jpg',Reina:'https://c-ssl.duitang.com/uploads/blog/202305/01/20230501125015_95235.jpg'};
  const esc=v=>String(v??'').replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]));
  const pinsKey=()=>`ruby_pinned_chats_${currentUser?.id||'guest'}`;const getPins=()=>{try{return JSON.parse(localStorage.getItem(pinsKey())||'[]')}catch{return[]}};const savePins=a=>localStorage.setItem(pinsKey(),JSON.stringify(a));
  const orderKey=()=>`ruby_pinned_order_${currentUser?.id||'guest'}`;const getOrder=()=>{try{return JSON.parse(localStorage.getItem(orderKey())||'[]')}catch{return[]}};const saveOrder=a=>localStorage.setItem(orderKey(),JSON.stringify(a));
  function loginRequired(){alert('Please log in or create an account to start chatting.');document.getElementById('rubyAuthButton')?.click()}
  async function getUser(){if(currentUser)return currentUser;const r=await db.auth.getSession();currentUser=r.data.session?.user||null;return currentUser}
  async function ensureConversation(character){if(!currentUser||!character)return null;let r=await db.from('conversations').select('*').eq('user_id',currentUser.id).eq('character_id',character).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;if(r.data)return r.data;r=await db.from('conversations').insert({user_id:currentUser.id,character_id:character,title:character+' Chat'}).select().single();if(r.error)throw r.error;return r.data}
  async function createNewConversation(character){const r=await db.from('conversations').insert({user_id:currentUser.id,character_id:character,title:'New '+character}).select().single();if(r.error)throw r.error;return r.data}
  async function addMessage(id,role,content){if(!currentUser||!id||!content)return false;const r=await db.from('messages').insert({conversation_id:id,user_id:currentUser.id,role,content});if(r.error)return false;db.from('conversations').update({updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',currentUser.id);return true}
  function styles(){if(document.getElementById('ruby-history-actions-style'))return;const s=document.createElement('style');s.id='ruby-history-actions-style';s.textContent=`.ruby-unified-history{position:relative;z-index:2;display:flex!important;align-items:center!important;gap:10px;width:100%;box-sizing:border-box;border:1px solid rgba(124,58,237,.12)!important;background:linear-gradient(135deg,#fff,#faf7ff)!important;box-shadow:0 6px 20px rgba(124,58,237,.06);transition:.18s;overflow:visible!important}.ruby-unified-history:hover{z-index:20;border-color:rgba(124,58,237,.28)!important;box-shadow:0 9px 25px rgba(124,58,237,.11)}.ruby-unified-history .chat-history-avatar{width:44px!important;height:44px!important;flex:0 0 44px;object-fit:cover;border-radius:12px}.ruby-unified-history .chat-history-info{min-width:0!important;flex:1!important;overflow:hidden}.ruby-unified-history .chat-history-name{display:flex!important;align-items:center;min-width:0;font-weight:800}.ruby-unified-history .chat-history-preview{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ruby-history-actions{display:flex;align-items:center;gap:5px;margin-left:auto;flex:0 0 auto;position:relative}.ruby-history-icon-btn{width:31px;height:31px;border:1px solid rgba(124,58,237,.12);border-radius:9px;background:#f7f3ff;color:#6d28d9;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;font-size:13px}.ruby-history-icon-btn:hover{background:#eee7ff}.ruby-history-menu{position:absolute!important;right:0!important;top:calc(100% + 6px)!important;bottom:auto!important;z-index:2147483647!important;display:none;width:175px;padding:6px;border:1px solid rgba(60,60,67,.12);border-radius:13px;background:rgba(255,255,255,.99);box-shadow:0 14px 38px rgba(0,0,0,.18);backdrop-filter:blur(12px)}.ruby-history-menu.show{display:block}.ruby-history-menu button{width:100%;border:0;background:none;padding:9px 10px;border-radius:9px;text-align:left;font-size:12px;cursor:pointer}.ruby-history-menu button:hover{background:#f2f2f7}.ruby-history-menu .delete{color:#dc2626}.ruby-new-chat-btn{margin-left:auto;border:0;border-radius:11px;padding:8px 10px;background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;font-size:11px;font-weight:800;cursor:pointer}.ruby-new-chat-btn:disabled{opacity:.55}.ruby-file-action{display:flex;align-items:center;gap:8px;width:100%;padding:9px 10px;border:0;background:none;border-radius:9px;text-align:left;font-size:12px;cursor:pointer}.ruby-file-action:hover{background:#f2f2f7}.ruby-file-action input{display:none}@media(max-width:600px){.ruby-unified-history{gap:8px}.ruby-unified-history .chat-history-avatar{width:40px!important;height:40px!important;flex-basis:40px}.ruby-history-actions .chat-history-time{display:none}.ruby-history-icon-btn{width:30px;height:30px}.ruby-history-menu{right:0!important;width:165px}}`;
    document.head.appendChild(s)}
  function ensureNewChatButton(){styles();const head=document.querySelector('#rubyKindroidChat .rk-head');if(!head||head.querySelector('#rubyNewChatBtn'))return;const b=document.createElement('button');b.id='rubyNewChatBtn';b.className='ruby-new-chat-btn';b.type='button';b.textContent='＋ New';b.onclick=startNewChat;head.appendChild(b)}
  async function startNewChat(){if(!await getUser())return loginRequired();const ch=window.rubyCurrentCharacter;if(!ch)return;const b=document.getElementById('rubyNewChatBtn');if(b)b.disabled=true;try{const c=await createNewConversation(ch);window.rubyCurrentConversation=c.id;window.rubyChatMessages=[];switchPage('chat');window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character:ch,conversation:c,messages:[]}}));loadHistory(true)}catch(e){console.error(e);alert('Could not start a new chat.')}finally{if(b)b.disabled=false}}
  function telegram(character){if(typeof window.rubyOpenTelegram==='function'){window.rubyOpenTelegram({id:character});return}const bot=String(window.RUBY_TELEGRAM_BOT_USERNAME||'Rubby_Chan_Bot').replace(/^@/,'');window.location.href=`https://t.me/${bot}?start=${encodeURIComponent('character_'+character)}`}
  async function renameConversation(c){const current=c.title||('Chat with '+c.character_id);const next=window.prompt('Rename chat',current);if(next===null)return;const title=next.trim();if(!title)return;const r=await db.from('conversations').update({title}).eq('id',c.id).eq('user_id',currentUser.id);if(r.error){alert('Could not rename this chat.');return}loadHistory(true)}
  async function deleteConversation(c){if(!confirm('Delete this conversation? This cannot be undone.'))return;const r=await db.from('conversations').delete().eq('id',c.id).eq('user_id',currentUser.id);if(r.error){alert('Could not delete this chat.');return}savePins(getPins().filter(x=>x!==c.id));saveOrder(getOrder().filter(x=>x!==c.id));if(window.rubyCurrentConversation===c.id){window.rubyCurrentConversation=null;window.rubyCurrentCharacter=null}loadHistory(true)}
  function togglePin(c){const p=getPins(),i=p.indexOf(c.id);if(i>=0)p.splice(i,1);else p.push(c.id);savePins(p);loadHistory(true)}
  function addFile(c){const input=document.createElement('input');input.type='file';input.accept='*/*';input.onchange=()=>{const file=input.files?.[0];if(file){alert(`Selected: ${file.name}`)}};input.click()}
  function menu(c,row){const m=document.createElement('div');m.className='ruby-history-menu';const pin=getPins().includes(c.id);m.innerHTML=`<button data-act="pin">${pin?'Unpin':'Pin'}</button><button data-act="rename">Rename</button><button data-act="telegram">Chat on Telegram</button><button data-act="file">Attach file</button><button data-act="delete" class="delete">Delete</button>`;row.querySelector('.ruby-history-actions').appendChild(m);m.querySelector('[data-act=pin]').onclick=e=>{e.stopPropagation();togglePin(c)};m.querySelector('[data-act=rename]').onclick=e=>{e.stopPropagation();renameConversation(c);m.classList.remove('show')};m.querySelector('[data-act=telegram]').onclick=e=>{e.stopPropagation();telegram(c.character_id);m.classList.remove('show')};m.querySelector('[data-act=file]').onclick=e=>{e.stopPropagation();addFile(c);m.classList.remove('show')};m.querySelector('[data-act=delete]').onclick=e=>{e.stopPropagation();deleteConversation(c)};return m}
  async function loadHistory(silent){if(!currentUser)return;const list=document.getElementById('chatHistoryList');if(!list)return;styles();let q=db.from('conversations').select('id,character_id,title,updated_at').eq('user_id',currentUser.id).order('updated_at',{ascending:false}).limit(100);if(historyCharacterFilter)q=q.eq('character_id',historyCharacterFilter);const r=await q;if(r.error)return;list.innerHTML='';if(!r.data?.length){const empty=document.createElement('div');empty.className='chat-empty';empty.innerHTML='💬<br><span>No chat history yet.</span>';list.appendChild(empty);return}const pins=getPins(),order=getOrder();r.data.sort((a,b)=>{const ap=pins.includes(a.id),bp=pins.includes(b.id);if(ap!==bp)return bp-ap;if(ap&&bp){const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return (ai<0?9999:ai)-(bi<0?9999:bi)}return new Date(b.updated_at)-new Date(a.updated_at)});r.data.forEach(c=>{const row=document.createElement('div');row.className='chat-history-item ruby-unified-history';row.dataset.chatId=c.id;row.draggable=true;const pinned=pins.includes(c.id);row.innerHTML=`<img class="chat-history-avatar" src="${images[c.character_id]||images.Sakura}" alt="${esc(c.character_id)}"><div class="chat-history-info"><div class="chat-history-name">${esc(c.title||('Chat with '+c.character_id))}</div><div class="chat-history-preview">${esc(c.character_id)} • Continue this conversation</div></div><div class="ruby-history-actions"><span class="chat-history-time">${new Date(c.updated_at).toLocaleDateString()}</span><button class="ruby-history-icon-btn" type="button" title="${pinned?'Unpin':'Pin'}">${pinned?'◆':'◇'}</button><button class="ruby-history-icon-btn" type="button" title="More">•••</button></div>`;row.onclick=()=>openConversation(c);const [pinBtn,moreBtn]=row.querySelectorAll('.ruby-history-icon-btn');pinBtn.onclick=e=>{e.stopPropagation();togglePin(c)};const mm=menu(c,row);moreBtn.onclick=e=>{e.stopPropagation();document.querySelectorAll('.ruby-history-menu.show').forEach(x=>x!==mm&&x.classList.remove('show'));mm.classList.toggle('show')};row.addEventListener('dragstart',()=>{row.dataset.dragging='1'});row.addEventListener('dragend',()=>{row.dataset.dragging='0';const ids=[...list.querySelectorAll('.ruby-unified-history')].filter(x=>pins.includes(x.dataset.chatId)).map(x=>x.dataset.chatId);saveOrder(ids)});row.addEventListener('dragover',e=>{e.preventDefault();const dragging=list.querySelector('[data-dragging="1"]');if(!dragging||dragging===row)return;const box=row.getBoundingClientRect();list.insertBefore(dragging,e.clientY<box.top+box.height/2?row:row.nextSibling)});list.appendChild(row)})}
  async function openConversation(c){if(!await getUser())return loginRequired();window.rubyCurrentConversation=c.id;window.rubyCurrentCharacter=c.character_id;historyCharacterFilter=null;switchPage('chat');const r=await db.from('messages').select('role,content,created_at').eq('conversation_id',c.id).order('created_at',{ascending:true});window.rubyChatMessages=r.error?[]:(r.data||[]);ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:loaded',{detail:{character:c.character_id,conversation:c,messages:window.rubyChatMessages}}))}
  window.rubyStartNewCharacterChat=async character=>{if(!await getUser())return loginRequired();const c=await createNewConversation(character);window.rubyCurrentConversation=c.id;window.rubyCurrentCharacter=character;window.rubyChatMessages=[];historyCharacterFilter=null;switchPage('chat');ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character,conversation:c,messages:[]}}));loadHistory(true)};
  window.rubyShowCharacterHistory=async character=>{if(!await getUser())return loginRequired();historyCharacterFilter=character;switchPage('chat');loadHistory(true)};
  window.rubyChatSaveMessage=async(role,content)=>{if(!await getUser())return false;let id=window.rubyCurrentConversation;if(!id){const c=await ensureConversation(window.rubyCurrentCharacter||'Unknown');id=c?.id;window.rubyCurrentConversation=id}if(!id)return false;const ok=await addMessage(id,role,content);loadHistory(true);return ok};window.rubyLoadChatHistory=loadHistory;
  window.startChat=async character=>{if(!await getUser())return loginRequired();window.rubyCurrentCharacter=character;const c=await ensureConversation(character);window.rubyCurrentConversation=c?.id||null;historyCharacterFilter=null;switchPage('chat');ensureNewChatButton();window.dispatchEvent(new CustomEvent('rubychat:open',{detail:{character,conversation:c}}))};
  db.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;if(currentUser)setTimeout(()=>loadHistory(true),0);else{window.rubyCurrentConversation=null;window.rubyCurrentCharacter=null}});
  function boot(){if(booted)return;booted=true;setTimeout(async()=>{await getUser();if(currentUser)loadHistory(true)},0)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();