/* Ruby Chan — Telegram handoff + account linking */
(function () {
  'use strict';
  const BOT_USERNAME=String(window.RUBY_TELEGRAM_BOT_USERNAME||'Rubby_Chan_Bot').replace(/^@/,'');
  const TELEGRAM_LINK_FUNCTION='https://hcbajvladlvhklelbxdr.supabase.co/functions/v1/bright-api';
  const getClient=()=>window.rubySupabase||window.supabaseClient||null;
  function telegramWebApp(){try{return window.Telegram?.WebApp||null}catch{return null}}
  function getTelegramContext(){const p=new URLSearchParams(window.location.search),u=telegramWebApp()?.initDataUnsafe?.user;return{chatId:p.get('telegram_chat_id')||(u?.id?String(u.id):''),characterId:p.get('character_id')||''}}
  async function getSession(){const c=getClient();if(!c?.auth?.getSession)return null;try{return(await c.auth.getSession()).data?.session||null}catch{return null}}
  function markLinked(ctx){localStorage.setItem('rubychan_telegram_linked','1');localStorage.setItem('rubychan_telegram_chat_id',ctx.chatId);if(ctx.characterId)localStorage.setItem('rubychan_telegram_character_id',ctx.characterId);telegramWebApp()?.ready?.()}
  async function linkTelegramAccount(){const c=getClient(),ctx=getTelegramContext(),s=await getSession();if(!c||!ctx.chatId||!s?.user?.id||!s?.access_token)return false;try{const r=await fetch(TELEGRAM_LINK_FUNCTION,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action:'link_telegram',telegram_chat_id:ctx.chatId,character_id:ctx.characterId||null})});const result=await r.json().catch(()=>({}));if(r.ok&&result?.ok){markLinked(ctx);return true}}catch(e){console.warn('Telegram link failed',e)}try{const{error:e}=await c.from('profiles').update({telegram_chat_id:String(ctx.chatId),updated_at:new Date().toISOString()}).eq('id',s.user.id);if(e)return false;if(ctx.characterId)await c.from('telegram_sessions').upsert({telegram_chat_id:String(ctx.chatId),character_id:ctx.characterId,updated_at:new Date().toISOString()},{onConflict:'telegram_chat_id'});markLinked(ctx);return true}catch{return false}}
  function styles(){if(document.getElementById('ruby-telegram-style'))return;const s=document.createElement('style');s.id='ruby-telegram-style';s.textContent=`.ruby-telegram-btn{display:flex;align-items:center;justify-content:center;gap:7px;flex:1;min-width:130px;margin-top:0;padding:10px 12px;border:1px solid rgba(124,58,237,.2);border-radius:12px;background:linear-gradient(135deg,#6d28d9,#a855f7);color:#fff;font:800 12px/1.1 Arial,sans-serif;cursor:pointer;box-shadow:0 6px 18px rgba(111,53,217,.18)}.ruby-telegram-history-btn{display:inline-flex;align-items:center;justify-content:center;margin-left:8px;width:34px;height:30px;border:0;border-radius:9px;background:#eee9ff;color:#6d28d9;cursor:pointer;font-size:16px;vertical-align:middle}.ruby-telegram-history-btn:hover{background:#e4d9ff}`;document.head.appendChild(s)}
  function openTelegram(character){const id=character?.id||character?.character_id;if(!id)return;window.location.href=`https://t.me/${BOT_USERNAME}?start=${encodeURIComponent('character_'+String(id).replace(/[^a-zA-Z0-9_-]/g,''))}`}
  function openTelegramHistory(){window.location.href=`https://t.me/${BOT_USERNAME}`}
  async function characterFromCard(card){const id=card.dataset.characterId||card.dataset.character||card.dataset.id,name=card.dataset.characterName||card.getAttribute('data-character-name')||card.querySelector('h3')?.textContent?.trim()||'';if(id)return{id,name};const c=getClient();if(c?.from&&name){const{data}=await c.from('characters').select('id,name,ai_id').eq('name',name).maybeSingle();return data||null}return null}
  async function addButtons(){styles();for(const card of document.querySelectorAll('.character-card')){if(card.querySelector('.ruby-telegram-btn'))continue;const b=document.createElement('button');b.type='button';b.className='ruby-telegram-btn';b.innerHTML='<span>✈️</span><span>Chat on Telegram</span>';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const ch=await characterFromCard(card);if(ch?.id)openTelegram(ch)};(card.querySelector('.ruby-character-actions')||card.querySelector('.character-content')||card.querySelector('.card-content')||card).appendChild(b)}}
  async function addHistoryButtons(){styles();const list=document.querySelector('.chat-history-list');if(!list)return;for(const item of list.querySelectorAll('.chat-history-item')){if(item.querySelector('.ruby-telegram-history-btn'))continue;const title=item.querySelector('.chat-history-name');if(!title)continue;const name=title.childNodes[0]?.textContent?.trim()||title.textContent.replace(/Platform \+ Telegram/i,'').trim();if(!name)continue;const c=getClient();if(!c?.from)continue;const{data:ch}=await c.from('characters').select('id,name').eq('name',name).maybeSingle();if(!ch?.id)continue;const b=document.createElement('button');b.type='button';b.className='ruby-telegram-history-btn';b.title='Chat on Telegram';b.setAttribute('aria-label','Chat on Telegram');b.textContent='✈️';b.onclick=e=>{e.preventDefault();e.stopPropagation();openTelegram(ch)};title.appendChild(b)}}
  function addHistoryStyles(){if(document.getElementById('ruby-unified-history-style'))return;const s=document.createElement('style');s.id='ruby-unified-history-style';s.textContent='.ruby-history-source{display:inline-flex;align-items:center;gap:4px;margin-left:7px;padding:3px 7px;border-radius:999px;background:#f1eaff;color:#6d28d9;font-size:9px;font-weight:800;vertical-align:middle}.ruby-telegram-history .chat-history-preview{color:#6d28d9}';document.head.appendChild(s)}
  function buildUnifiedHistory(){addHistoryStyles();const list=document.querySelector('.chat-history-list');if(!list)return;list.querySelectorAll('.ruby-telegram-history').forEach(e=>e.remove());list.querySelectorAll('.chat-history-item').forEach(item=>{const title=item.querySelector('.chat-history-name');if(!title||title.querySelector('.ruby-history-source'))return;const source=document.createElement('span');source.className='ruby-history-source';source.textContent='Platform + Telegram';title.appendChild(source);const preview=item.querySelector('.chat-history-preview');if(preview)preview.textContent='One shared conversation • chat anywhere'})}
  function init(){telegramWebApp()?.ready?.();telegramWebApp()?.expand?.();addButtons();buildUnifiedHistory();addHistoryButtons();let attempts=0;const tryLink=async()=>{attempts++;const ok=await linkTelegramAccount();if(!ok&&attempts<20)setTimeout(tryLink,1000)};tryLink();const c=getClient();if(c?.auth?.onAuthStateChange)c.auth.onAuthStateChange(()=>setTimeout(linkTelegramAccount,150));if(document.body)new MutationObserver(()=>{addButtons();buildUnifiedHistory();addHistoryButtons()}).observe(document.body,{childList:true,subtree:true})}
  window.rubyOpenTelegram=openTelegram;window.rubyOpenTelegramHistory=openTelegramHistory;window.rubyTelegramUrl=id=>`https://t.me/${BOT_USERNAME}?start=${encodeURIComponent('character_'+id)}`;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();